SELECT info.REST_ID AS REST_ID, 
info.REST_NAME AS REST_NAME, 
info.FOOD_TYPE AS FOOD_TYPE, 
info.FAVORITES AS FAVORITES, 
info.ADDRESS AS ADDRESS, 
ROUND(AVG(review.REVIEW_SCORE), 2) AS SCORE

FROM REST_INFO AS info LEFT JOIN REST_REVIEW AS review
ON info.REST_ID = review.REST_ID

WHERE SUBSTRING(info.ADDRESS, 1, 2) = '서울'
AND review.REVIEW_SCORE IS NOT NULL

GROUP BY info.REST_ID, info.REST_NAME, info.FOOD_TYPE, info.FAVORITES, info.ADDRESS
ORDER BY SCORE DESC, info.FAVORITES DESC